command: docker model configure
short: Configure runtime options globally or for a specific model
long: Configure runtime options globally or for a specific model
usage: docker model configure [--disable-loader-memory-check] [MODEL [--context-size=<n>] [--speculative-draft-model=<model>] [-- <runtime-flags...>]]
pname: docker model
plink: docker_model.yaml
options:
    - option: context-size
      value_type: int64
      default_value: "-1"
      description: context size (in tokens)
      deprecated: false
      hidden: false
      experimental: false
      experimentalcli: false
      kubernetes: false
      swarm: false
    - option: disable-loader-memory-check
      value_type: bool
      default_value: "false"
      description: disable memory checks in the model loader
      deprecated: false
      hidden: false
      experimental: false
      experimentalcli: false
      kubernetes: false
      swarm: false
    - option: speculative-draft-model
      value_type: string
      description: draft model for speculative decoding
      deprecated: false
      hidden: false
      experimental: false
      experimentalcli: false
      kubernetes: false
      swarm: false
    - option: speculative-min-acceptance-rate
      value_type: float64
      default_value: "0"
      description: minimum acceptance rate for speculative decoding
      deprecated: false
      hidden: false
      experimental: false
      experimentalcli: false
      kubernetes: false
      swarm: false
    - option: speculative-num-tokens
      value_type: int
      default_value: "0"
      description: number of tokens to predict speculatively
      deprecated: false
      hidden: false
      experimental: false
      experimentalcli: false
      kubernetes: false
      swarm: false
deprecated: false
hidden: true
experimental: false
experimentalcli: false
kubernetes: false
swarm: false

